version: '3.7'
services:
  rabbitmg:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  #rabbit amqp port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin #기본 사용자 이름
      - RABBITMQ_DEFAULT_PASS=admin123!@# #기본 사용자 비밀번호